# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2sp-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: wso2sp-worker
    node: wso2sp-worker
    pattern: wso2sp-pattern-distributed
spec:
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: wso2sp-worker
        node: wso2sp-worker
        pattern: wso2sp-pattern-distributed
    spec:
      containers:
      -
        image: docker.wso2.com/wso2sp-worker:4.2.0
        name: wso2sp-worker
        imagePullPolicy: IfNotPresent
        env:
        -
          name: WSO2_SERVER_PROFILE
          value: "worker"
        -
          name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          value: wso2sp-worker

        ports:
        -
          containerPort: 9090
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        -
          containerPort: 9543
          protocol: "TCP"
        -
          containerPort: 9711
          protocol: "TCP"
        -
          containerPort: 9611
          protocol: "TCP"
        -
          containerPort: 7711
          protocol: "TCP"
        -
          containerPort: 7611
          protocol: "TCP"

        volumeMounts:
        - name: sp-worker-conf
          mountPath: "/home/wso2carbon/kubernetes-volumes/worker/conf/"
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 300
          periodSeconds: 20
      imagePullSecrets:
      - name: wso2creds
      serviceAccountName: {{ .Values.svcaccount }}
      volumes:
      - name: sp-worker-conf
        configMap:
          name: sp-worker-conf
